### ISSUE TITLE
bsampler crash

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairMQ#193]
When running the `fairmq/test/sdk/test_topo.xml` after the control sequence
```
INIT DEVICE -> COMPLETE INIT -> RESET DEVICE -> INIT DEVICE -> COMPLETE INIT -> BIND
```
the bsampler segfaults with message
```
fairmq-bsampler: tpp.c:82: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.
```
Trace:
```
>>> info thread
  Id   Target Id                        Frame
* 1    Thread 0x7f7db89c9140 (LWP 3322) 0x00007f7dbaf6beb5 in raise () from /lib64/libc.so.6
  2    Thread 0x7f7db7780700 (LWP 3332) 0x00007f7dbb10c2b5 in nanosleep () from /lib64/libpthread.so.0
  3    Thread 0x7f7db6f7f700 (LWP 3335) 0x00007f7dbb10c2b5 in nanosleep () from /lib64/libpthread.so.0
  4    Thread 0x7f7db4b14700 (LWP 3341) 0x00007f7dbb1084e5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  5    Thread 0x7f7db5315700 (LWP 3340) 0x00007f7dbb1084e5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  6    Thread 0x7f7db5b16700 (LWP 3339) 0x00007f7dbb1084e5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
>>> bt
#0  0x00007f7dbaf6beb5 in raise () from /lib64/libc.so.6
#1  0x00007f7dbaf56895 in abort () from /lib64/libc.so.6
#2  0x00007f7dbaf56769 in __assert_fail_base.cold () from /lib64/libc.so.6
#3  0x00007f7dbaf645b6 in __assert_fail () from /lib64/libc.so.6
#4  0x00007f7dbb10dc44 in __pthread_tpp_change_priority () from /lib64/libpthread.so.0
#5  0x00007f7dbb1048f0 in __pthread_mutex_lock_full () from /lib64/libpthread.so.0
#6  0x00007f7dbb8b8c56 in __gthread_mutex_lock (__mutex=0xf1da20) at /usr/include/c++/9/x86_64-redhat-linux/bits/gthr-default.h:749
#7  std::mutex::lock (this=0xf1da20) at /usr/include/c++/9/bits/std_mutex.h:100
#8  std::lock_guard<std::mutex>::lock_guard (__m=..., this=<synthetic pointer>) at /usr/include/c++/9/bits/std_mutex.h:159
#9  FairMQChannel::Validate (this=0xf1d950) at ../fairmq/FairMQChannel.cxx:489
#10 0x00007f7dbb8d99b5 in FairMQDevice::AttachChannels (this=0xf0f6a0, chans=std::vector of length 2, capacity 2 = {...}) at ../fairmq/FairMQDevice.cxx:389
#11 0x00007f7dbb8d9bc0 in FairMQDevice::BindWrapper (this=0xf0f6a0) at ../fairmq/FairMQDevice.cxx:335
#12 0x00007f7dbb8ddf28 in FairMQDevice::<lambda(fair::mq::State)>::operator()(fair::mq::State) (state=fair::mq::State::Binding, __closure=<optimized out>) at ../fairmq/FairMQDevice.cxx:155
#13 0x00007f7dbb524dcd in std::function<void (fair::mq::State)>::operator()(fair::mq::State) const (__args#0=<optimized out>, this=<optimized out>) at /usr/include/c++/9/bits/std_function.h:685
#14 boost::detail::function::void_function_obj_invoker1<std::function<void (fair::mq::State)>, void, fair::mq::State>::invoke(boost::detail::function::function_buffer&, fair::mq::State) (function_obj_ptr=..., a0=<optimized out>) at /usr/include/boost/function/function_template.hpp:158
#15 0x00007f7dbb52ee19 in boost::function1<void, fair::mq::State>::operator() (a0=<optimized out>, this=<optimized out>) at /usr/include/boost/function/function_template.hpp:677
#16 boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void (fair::mq::State)>, 0u, fair::mq::State&>(boost::function<void (fair::mq::State)>&, boost::signals2::detail::unsigned_meta_array<0u>, std::tuple<fair::mq::State&> const&, boost::enable_if<boost::is_void<boost::function<void (fair::mq::State)>::result_type>, void>::type*) const (this=<optimized out>, args=std::tuple containing = {...}, func=...) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:105
#17 boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void (fair::mq::State)>, fair::mq::State&, 1ul>(boost::function<void (fair::mq::State)>&, std::tuple<fair::mq::State&> const&, mpl_::size_t<1ul>) const (this=<optimized out>, args=std::tuple containing = {...}, func=...) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:90
#18 boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, fair::mq::State>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > const&) const (connectionBody=..., this=0x7ffc33e3ffd0) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:133
#19 boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, fair::mq::State>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> >::dereference() const (this=0x7ffc33e3fe00) at /usr/include/boost/signals2/detail/slot_call_iterator.hpp:110
#20 boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, fair::mq::State>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, fair::mq::State>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > const&) (f=...) at /usr/include/boost/iterator/iterator_facade.hpp:550
#21 boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, fair::mq::State>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> >, boost::signals2::detail::void_type, boost::iterators::single_pass_traversal_tag, boost::signals2::detail::void_type const&, long, false, false>::operator*() const (this=0x7ffc33e3fe00) at /usr/include/boost/iterator/iterator_facade.hpp:656
#22 boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, fair::mq::State>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, fair::mq::State>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, fair::mq::State>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> >) const (last=..., first=..., this=<optimized out>) at /usr/include/boost/signals2/optional_last_value.hpp:57
#23 boost::signals2::detail::combiner_invoker<void>::operator()<boost::signals2::optional_last_value<void>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, fair::mq::State>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > >(boost::signals2::optional_last_value<void>&, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, fair::mq::State>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, fair::mq::State>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (fair::mq::State), boost::function<void (fair::mq::State)> >, boost::signals2::mutex> >) const (this=<optimized out>, last=..., first=..., combiner=...) at /usr/include/boost/signals2/detail/result_type_wrapper.hpp:64
#24 boost::signals2::detail::signal_impl<void (fair::mq::State), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (fair::mq::State)>, boost::function<void (boost::signals2::connection const&, fair::mq::State)>, boost::signals2::mutex>::operator()(fair::mq::State) (this=0xf12fa0, args#0=<optimized out>, args#0@entry=fair::mq::State::Binding) at /usr/include/boost/signals2/detail/signal_template.hpp:243
#25 0x00007f7dbb537d6f in boost::signals2::signal<void (fair::mq::State), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (fair::mq::State)>, boost::function<void (boost::signals2::connection const&, fair::mq::State)>, boost::signals2::mutex>::operator()(fair::mq::State) const (args#0=fair::mq::State::Binding, this=0xf12d70) at /usr/include/boost/signals2/detail/signal_template.hpp:724
#26 fair::mq::fsm::Machine_::CallStateHandler (state=fair::mq::State::Binding, this=0xf12ce0) at ../fairmq/StateMachine.cxx:156
#27 fair::mq::fsm::Machine_::ProcessWork (this=0xf12ce0) at ../fairmq/StateMachine.cxx:204
#28 0x00007f7dbb5234dd in fair::mq::StateMachine::ProcessWork (this=0xf0f760) at /usr/include/c++/9/bits/shared_ptr_base.h:1020
#29 0x00007f7dbb8a60ec in FairMQDevice::RunStateMachine (this=<optimized out>) at ../fairmq/FairMQDevice.h:434
#30 fair::mq::DeviceRunner::Run (this=this@entry=0x7ffc33e41290) at ../fairmq/DeviceRunner.cxx:173
#31 0x000000000041a3f7 in main (argc=<optimized out>, argv=<optimized out>) at ../fairmq/runFairMQDevice.h:51
```

**Comment by dennisklein** [comment]
cannot reproduce it any more
